import 'dart:io';
import 'dart:math';
void main(){
  int num,userGuess;
  Random random=Random();
  num=random.nextInt(100)+1;
  print('A number has been generated by the system\n from 1 to 100.\n Try to guess it.');
   while(true){
     stdout.write('Enter your guess:');
   int  userGuess=int.parse(stdin.readLineSync()!);
         if(userGuess > num){
        print("your guess is high,try again");
                            }
       else if(userGuess < num){
        print("your guess is low,try again"); 
                               }
       else{
                break;
           }
       }
       print("Congratulations,you have guessed the number");      
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 